export const GET_ALL_LEADER_REQUEST = "GET_ALL_LEADER_REQUEST";
export const GET_ALL_LEADER_FAILURE = "GET_ALL_LEADER_FAILURE";
export const GET_ALL_LEADER_SUCCESS = "GET_ALL_LEADER_SUCCESS";

export const GET_SEARCH_LEADER_REQUEST = "GET_SEARCH_LEADER_REQUEST";
export const GET_SEARCH_LEADER_FAILURE = "GET_SEARCH_LEADER_FAILURE";
export const GET_SEARCH_LEADER_SUCCESS = "GET_SEARCH_LEADER_SUCCESS";

export const GET_ALL_BUDGET_REQUEST = "GET_ALL_BUDGET_REQUEST";
export const GET_ALL_BUDGET_FAILURE = "GET_ALL_BUDGET_FAILURE";
export const GET_ALL_BUDGET_SUCCESS = "GET_ALL_BUDGET_SUCCESS";

export const GET_SEARCH_BUDGET_REQUEST = "GET_SEARCH_BUDGET_REQUEST";
export const GET_SEARCH_BUDGET_FAILURE = "GET_SEARCH_BUDGET_FAILURE";
export const GET_SEARCH_BUDGET_SUCCESS = "GET_SEARCH_BUDGET_SUCCESS";

export const GET_ALL_PLANS_REQUEST = "GET_ALL_PLANS_REQUEST";
export const GET_ALL_PLANS_FAILURE = "GET_ALL_PLANS_FAILURE";
export const GET_ALL_PLANS_SUCCESS = "GET_ALL_PLANS_SUCCESS";

export const GET_SEARCH_PLANS_REQUEST = "GET_SEARCH_PLANS_REQUEST";
export const GET_SEARCH_PLANS_FAILURE = "GET_SEARCH_PLANS_FAILURE";
export const GET_SEARCH_PLANS_SUCCESS = "GET_SEARCH_PLANS_SUCCESS";

export const GET_ALL_HELP_REQUEST = "GET_ALL_HELP_REQUEST";
export const GET_ALL_HELP_FAILURE = "GET_ALL_HELP_FAILURE";
export const GET_ALL_HELP_SUCCESS = "GET_ALL_HELP_SUCCESS";


export const GET_ALL_TOURIST_REQUEST = "GET_ALL_TOURIST_REQUEST";
export const GET_ALL_TOURIST_FAILURE = "GET_ALL_TOURIST_FAILURE";
export const GET_ALL_TOURIST_SUCCESS = "GET_ALL_TOURIST_SUCCESS";
